use std::path::Path;
use std::process::{Command, ExitStatus, Stdio};

fn main() {
    let mut args = std::env::args();
    args.next();

    let mut base_revision = None;
    let mut target = None;
    while let Some(arg) = args.next() {
        if let Some(val) = parse_arg(&arg, &mut args, "base-revision") {
            base_revision = Some(val);
        } else if let Some(val) = parse_arg(&arg, &mut args, "target") {
            target = Some(val);
        } else {
            eprintln!("unexpected argument {arg}");
            std::process::exit(1);
        }
    }

    // Make sure the work tree is clean.
    Command::new("git")
        .args(["diff-index", "--quiet", "HEAD", "--"])
        .run()
        .exit_on_failure("git work tree is dirty, commit or stash your changes");

    let text;
    let (revs, mut missing) = if let Some(base_rev) = &base_revision {
        // When comparing against a base revision, only rerun if the test
        // references actually changed.
        let status = Command::new("git")
            .args(["diff-tree", "--quiet", "-r", "HEAD", base_rev, "--", "tests/ref"])
            .run();
        if status.success() {
            println!("test references weren't changed");
            return;
        }

        (vec![base_rev.as_str()], Vec::new())
    } else {
        text = match std::fs::read_to_string("tests/store/missing.txt") {
            Ok(text) => text,
            Err(_) => {
                println!("no `tests/store/missing.txt`");
                return;
            }
        };

        parse_missing(&text).unwrap_or_else(|err| {
            println!("failed to parse `tests/store/missing.txt`: {err}");
            std::process::exit(1);
        })
    };

    // Run tests for at most 3 old revisions.
    let target = target.map(|target| format!("--target={target}"));
    for rev in revs.iter().take(3) {
        read_tree(rev);

        let missing_names = missing
            .chunk_by(|a, b| test_name(a) == test_name(b))
            .map(|paths| test_name(paths[0]));
        // Allow a failing test suite.
        let status = Command::new("cargo")
            .args(["test", "--workspace", "--test=tests"])
            .args(&target)
            .args(["--", "--no-report", "--stages=svg,pdf"])
            .args(["--", "--exact"])
            .args(missing_names)
            .run();

        // If the test suite passes, there aren't any more missing live output.
        if status.success() {
            break;
        }

        // Even a failing test suite could produce all missing live output.
        // Check if there are any more paths missing.
        missing.retain(|path| !Path::new(path).exists());
        if missing.is_empty() {
            break;
        }
    }

    read_tree("HEAD");

    // Allow a failing test suite.
    let base_rev = base_revision.map(|rev| format!("--base-revision={rev}"));
    Command::new("cargo")
        .args(["test", "--workspace", "--test=tests"])
        .args(&target)
        .arg("--")
        .args(&base_rev)
        .run();
}

fn parse_arg(arg: &str, args: &mut std::env::Args, name: &str) -> Option<String> {
    let arg = arg.strip_prefix("--")?;
    let remainder = arg.strip_prefix(name)?;

    if let Some(val) = remainder.strip_prefix("=") {
        Some(val.to_string())
    } else {
        Some(args.next().unwrap_or_else(|| {
            eprintln!("expected value of --{name}");
            std::process::exit(1);
        }))
    }
}

/// Parse the `tests/store/missing.txt` file generated by the tests suite report.
fn parse_missing(text: &str) -> Result<(Vec<&str>, Vec<&str>), &'static str> {
    // Although we have the exact commits at which the hash refernces were
    // added, it's probably a good idea to recompile a more recent commit that
    // won't have to compile a completely different dependency tree.
    //
    // That's why we try the last commit at which a hash reference was added
    // first. Unless the test suite was failing at that commit this will produce
    // all missing references.
    let mut lines = text.lines().peekable();
    let newest_update_rev = (lines.next())
        .and_then(|line| line.strip_prefix("newest-update-rev: "))
        .ok_or("expected newest-update-rev")?;

    let mut revs = vec![newest_update_rev];
    if lines.next() != Some("missing-old-revs:") {
        return Err("expected missing-old-revs");
    }
    while let Some(line) = lines.peek() {
        let Some(rev) = line.strip_prefix("- ") else { break };
        if !revs.contains(&rev) {
            revs.push(rev);
        }
        lines.next();
    }

    let mut missing = Vec::new();
    if lines.next() != Some("missing-live:") {
        return Err("expected missing-live");
    }
    while let Some(line) = lines.peek() {
        let Some(path) = line.strip_prefix("- ") else { break };
        missing.push(path);
        lines.next();
    }

    Ok((revs, missing))
}

fn test_name(hash_path: &str) -> &str {
    let start = hash_path.rfind('_').unwrap() + 1;
    let end = hash_path.rfind('.').unwrap();
    &hash_path[start..end]
}

fn read_tree(rev: &str) {
    println!("checking out `{rev}`");
    Command::new("git")
        .args(["read-tree", "-um", rev])
        .stdin(Stdio::null())
        .run()
        .exit_on_failure("failed to checkout `{rev}`");
}

trait Run {
    fn run(&mut self) -> ExitStatus;
}

impl Run for Command {
    fn run(&mut self) -> ExitStatus {
        print!("> {}", self.get_program().display());
        for arg in self.get_args() {
            print!(" {}", arg.display());
        }
        println!();
        self.spawn().unwrap().wait().unwrap()
    }
}

trait ExitOnFailure {
    fn exit_on_failure(self, msg: &str);
}

impl ExitOnFailure for ExitStatus {
    fn exit_on_failure(self, msg: &str) {
        if !self.success() {
            eprintln!("{msg}");
            std::process::exit(self.code().unwrap_or(1));
        }
    }
}
