name: 💻 Web App Bug Report
description: For issues specific to https://typst.app
title: Write a short and descriptive title!
labels:
  - bug
  - web app
assignees:
  - reknih
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug on the Typst web app. Did you [take a look](https://github.com/typst/typst/issues?q=is%3Aopen+is%3Aissue+label%3A%22web+app%22+label%3Abug) if your issue has already been filed? If so, join the discussion there!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your issue. Include specific steps to reproduce it or a screenshot if the problem is visual.
      placeholder: Terse and specific description of the bug. You can add a screenshot by dragging an image here.
    validations:
      required: true
  - type: input
    id: repro-url
    attributes:
      label: Reproduction URL
      description: If your issue involves a project and you did not specify Typst code above, you can share a link to your project here
      placeholder: https://typst.app/project/rU6j4Q5foiCcvB7Hz_gs9m
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: Which operating system did you use?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - Android
        - iOS or iPad OS
    validations:
      required: false
