name: 🎁 Web App Feature Request
description: For feature requests specific to https://typst.app
title: Write a short and descriptive title!
labels:
  - feature request
  - web app
assignees:
  - reknih
body:
  - type: markdown
    attributes:
      value: Thanks for sharing your feature request for the Typst web app. Did you [take a look](https://github.com/typst/typst/issues?q=is%3Aopen+is%3Aissue+label%3Abug+label%3A%22feature+request%22) if a similar request has already been filed? If so, join the discussion there!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your feature request. You can also add a mockup!
      placeholder: Terse and specific description of the feature. You can add an image by dragging a file here.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Please describe why this feature would be useful.
      placeholder: Describe what users can accomplish with this feature and whom it might be useful for.
    validations:
      required: true
