// This file is generated by `tools/codegen/src/html.rs`.
// Do not edit by hand.

#![cfg_attr(rustfmt, rustfmt_skip)]

use std::num::NonZeroU64;

use crate::foundations::{Datetime, Duration, PositiveF64, Smart, Str};
use crate::html::typed::*;
use crate::visualize::Color;

#[allow(non_upper_case_globals)]
pub mod tag {
    use crate::html::HtmlTag;
    pub const a: HtmlTag = HtmlTag::constant("a");
    pub const abbr: HtmlTag = HtmlTag::constant("abbr");
    pub const address: HtmlTag = HtmlTag::constant("address");
    pub const area: HtmlTag = HtmlTag::constant("area");
    pub const article: HtmlTag = HtmlTag::constant("article");
    pub const aside: HtmlTag = HtmlTag::constant("aside");
    pub const audio: HtmlTag = HtmlTag::constant("audio");
    pub const b: HtmlTag = HtmlTag::constant("b");
    pub const base: HtmlTag = HtmlTag::constant("base");
    pub const bdi: HtmlTag = HtmlTag::constant("bdi");
    pub const bdo: HtmlTag = HtmlTag::constant("bdo");
    pub const blockquote: HtmlTag = HtmlTag::constant("blockquote");
    pub const body: HtmlTag = HtmlTag::constant("body");
    pub const br: HtmlTag = HtmlTag::constant("br");
    pub const button: HtmlTag = HtmlTag::constant("button");
    pub const canvas: HtmlTag = HtmlTag::constant("canvas");
    pub const caption: HtmlTag = HtmlTag::constant("caption");
    pub const cite: HtmlTag = HtmlTag::constant("cite");
    pub const code: HtmlTag = HtmlTag::constant("code");
    pub const col: HtmlTag = HtmlTag::constant("col");
    pub const colgroup: HtmlTag = HtmlTag::constant("colgroup");
    pub const data: HtmlTag = HtmlTag::constant("data");
    pub const datalist: HtmlTag = HtmlTag::constant("datalist");
    pub const dd: HtmlTag = HtmlTag::constant("dd");
    pub const del: HtmlTag = HtmlTag::constant("del");
    pub const details: HtmlTag = HtmlTag::constant("details");
    pub const dfn: HtmlTag = HtmlTag::constant("dfn");
    pub const dialog: HtmlTag = HtmlTag::constant("dialog");
    pub const div: HtmlTag = HtmlTag::constant("div");
    pub const dl: HtmlTag = HtmlTag::constant("dl");
    pub const dt: HtmlTag = HtmlTag::constant("dt");
    pub const em: HtmlTag = HtmlTag::constant("em");
    pub const embed: HtmlTag = HtmlTag::constant("embed");
    pub const fieldset: HtmlTag = HtmlTag::constant("fieldset");
    pub const figcaption: HtmlTag = HtmlTag::constant("figcaption");
    pub const figure: HtmlTag = HtmlTag::constant("figure");
    pub const footer: HtmlTag = HtmlTag::constant("footer");
    pub const form: HtmlTag = HtmlTag::constant("form");
    pub const h1: HtmlTag = HtmlTag::constant("h1");
    pub const h2: HtmlTag = HtmlTag::constant("h2");
    pub const h3: HtmlTag = HtmlTag::constant("h3");
    pub const h4: HtmlTag = HtmlTag::constant("h4");
    pub const h5: HtmlTag = HtmlTag::constant("h5");
    pub const h6: HtmlTag = HtmlTag::constant("h6");
    pub const head: HtmlTag = HtmlTag::constant("head");
    pub const header: HtmlTag = HtmlTag::constant("header");
    pub const hgroup: HtmlTag = HtmlTag::constant("hgroup");
    pub const hr: HtmlTag = HtmlTag::constant("hr");
    pub const html: HtmlTag = HtmlTag::constant("html");
    pub const i: HtmlTag = HtmlTag::constant("i");
    pub const iframe: HtmlTag = HtmlTag::constant("iframe");
    pub const img: HtmlTag = HtmlTag::constant("img");
    pub const input: HtmlTag = HtmlTag::constant("input");
    pub const ins: HtmlTag = HtmlTag::constant("ins");
    pub const kbd: HtmlTag = HtmlTag::constant("kbd");
    pub const label: HtmlTag = HtmlTag::constant("label");
    pub const legend: HtmlTag = HtmlTag::constant("legend");
    pub const li: HtmlTag = HtmlTag::constant("li");
    pub const link: HtmlTag = HtmlTag::constant("link");
    pub const main: HtmlTag = HtmlTag::constant("main");
    pub const map: HtmlTag = HtmlTag::constant("map");
    pub const mark: HtmlTag = HtmlTag::constant("mark");
    pub const menu: HtmlTag = HtmlTag::constant("menu");
    pub const meta: HtmlTag = HtmlTag::constant("meta");
    pub const meter: HtmlTag = HtmlTag::constant("meter");
    pub const nav: HtmlTag = HtmlTag::constant("nav");
    pub const noscript: HtmlTag = HtmlTag::constant("noscript");
    pub const object: HtmlTag = HtmlTag::constant("object");
    pub const ol: HtmlTag = HtmlTag::constant("ol");
    pub const optgroup: HtmlTag = HtmlTag::constant("optgroup");
    pub const option: HtmlTag = HtmlTag::constant("option");
    pub const output: HtmlTag = HtmlTag::constant("output");
    pub const p: HtmlTag = HtmlTag::constant("p");
    pub const picture: HtmlTag = HtmlTag::constant("picture");
    pub const pre: HtmlTag = HtmlTag::constant("pre");
    pub const progress: HtmlTag = HtmlTag::constant("progress");
    pub const q: HtmlTag = HtmlTag::constant("q");
    pub const rp: HtmlTag = HtmlTag::constant("rp");
    pub const rt: HtmlTag = HtmlTag::constant("rt");
    pub const ruby: HtmlTag = HtmlTag::constant("ruby");
    pub const s: HtmlTag = HtmlTag::constant("s");
    pub const samp: HtmlTag = HtmlTag::constant("samp");
    pub const script: HtmlTag = HtmlTag::constant("script");
    pub const search: HtmlTag = HtmlTag::constant("search");
    pub const section: HtmlTag = HtmlTag::constant("section");
    pub const select: HtmlTag = HtmlTag::constant("select");
    pub const slot: HtmlTag = HtmlTag::constant("slot");
    pub const small: HtmlTag = HtmlTag::constant("small");
    pub const source: HtmlTag = HtmlTag::constant("source");
    pub const span: HtmlTag = HtmlTag::constant("span");
    pub const strong: HtmlTag = HtmlTag::constant("strong");
    pub const style: HtmlTag = HtmlTag::constant("style");
    pub const sub: HtmlTag = HtmlTag::constant("sub");
    pub const summary: HtmlTag = HtmlTag::constant("summary");
    pub const sup: HtmlTag = HtmlTag::constant("sup");
    pub const table: HtmlTag = HtmlTag::constant("table");
    pub const tbody: HtmlTag = HtmlTag::constant("tbody");
    pub const td: HtmlTag = HtmlTag::constant("td");
    pub const template: HtmlTag = HtmlTag::constant("template");
    pub const textarea: HtmlTag = HtmlTag::constant("textarea");
    pub const tfoot: HtmlTag = HtmlTag::constant("tfoot");
    pub const th: HtmlTag = HtmlTag::constant("th");
    pub const thead: HtmlTag = HtmlTag::constant("thead");
    pub const time: HtmlTag = HtmlTag::constant("time");
    pub const title: HtmlTag = HtmlTag::constant("title");
    pub const tr: HtmlTag = HtmlTag::constant("tr");
    pub const track: HtmlTag = HtmlTag::constant("track");
    pub const u: HtmlTag = HtmlTag::constant("u");
    pub const ul: HtmlTag = HtmlTag::constant("ul");
    pub const var: HtmlTag = HtmlTag::constant("var");
    pub const video: HtmlTag = HtmlTag::constant("video");
    pub const wbr: HtmlTag = HtmlTag::constant("wbr");
}

#[allow(non_upper_case_globals)]
pub mod attr {
    use crate::html::HtmlAttr;
    pub const abbr: HtmlAttr = HtmlAttr::constant("abbr");
    pub const accept: HtmlAttr = HtmlAttr::constant("accept");
    pub const accept_charset: HtmlAttr = HtmlAttr::constant("accept-charset");
    pub const accesskey: HtmlAttr = HtmlAttr::constant("accesskey");
    pub const action: HtmlAttr = HtmlAttr::constant("action");
    pub const allow: HtmlAttr = HtmlAttr::constant("allow");
    pub const allowfullscreen: HtmlAttr = HtmlAttr::constant("allowfullscreen");
    pub const alpha: HtmlAttr = HtmlAttr::constant("alpha");
    pub const alt: HtmlAttr = HtmlAttr::constant("alt");
    pub const aria_activedescendant: HtmlAttr = HtmlAttr::constant("aria-activedescendant");
    pub const aria_atomic: HtmlAttr = HtmlAttr::constant("aria-atomic");
    pub const aria_autocomplete: HtmlAttr = HtmlAttr::constant("aria-autocomplete");
    pub const aria_busy: HtmlAttr = HtmlAttr::constant("aria-busy");
    pub const aria_checked: HtmlAttr = HtmlAttr::constant("aria-checked");
    pub const aria_colcount: HtmlAttr = HtmlAttr::constant("aria-colcount");
    pub const aria_colindex: HtmlAttr = HtmlAttr::constant("aria-colindex");
    pub const aria_colspan: HtmlAttr = HtmlAttr::constant("aria-colspan");
    pub const aria_controls: HtmlAttr = HtmlAttr::constant("aria-controls");
    pub const aria_current: HtmlAttr = HtmlAttr::constant("aria-current");
    pub const aria_describedby: HtmlAttr = HtmlAttr::constant("aria-describedby");
    pub const aria_details: HtmlAttr = HtmlAttr::constant("aria-details");
    pub const aria_disabled: HtmlAttr = HtmlAttr::constant("aria-disabled");
    pub const aria_errormessage: HtmlAttr = HtmlAttr::constant("aria-errormessage");
    pub const aria_expanded: HtmlAttr = HtmlAttr::constant("aria-expanded");
    pub const aria_flowto: HtmlAttr = HtmlAttr::constant("aria-flowto");
    pub const aria_haspopup: HtmlAttr = HtmlAttr::constant("aria-haspopup");
    pub const aria_hidden: HtmlAttr = HtmlAttr::constant("aria-hidden");
    pub const aria_invalid: HtmlAttr = HtmlAttr::constant("aria-invalid");
    pub const aria_keyshortcuts: HtmlAttr = HtmlAttr::constant("aria-keyshortcuts");
    pub const aria_label: HtmlAttr = HtmlAttr::constant("aria-label");
    pub const aria_labelledby: HtmlAttr = HtmlAttr::constant("aria-labelledby");
    pub const aria_level: HtmlAttr = HtmlAttr::constant("aria-level");
    pub const aria_live: HtmlAttr = HtmlAttr::constant("aria-live");
    pub const aria_modal: HtmlAttr = HtmlAttr::constant("aria-modal");
    pub const aria_multiline: HtmlAttr = HtmlAttr::constant("aria-multiline");
    pub const aria_multiselectable: HtmlAttr = HtmlAttr::constant("aria-multiselectable");
    pub const aria_orientation: HtmlAttr = HtmlAttr::constant("aria-orientation");
    pub const aria_owns: HtmlAttr = HtmlAttr::constant("aria-owns");
    pub const aria_placeholder: HtmlAttr = HtmlAttr::constant("aria-placeholder");
    pub const aria_posinset: HtmlAttr = HtmlAttr::constant("aria-posinset");
    pub const aria_pressed: HtmlAttr = HtmlAttr::constant("aria-pressed");
    pub const aria_readonly: HtmlAttr = HtmlAttr::constant("aria-readonly");
    pub const aria_relevant: HtmlAttr = HtmlAttr::constant("aria-relevant");
    pub const aria_required: HtmlAttr = HtmlAttr::constant("aria-required");
    pub const aria_roledescription: HtmlAttr = HtmlAttr::constant("aria-roledescription");
    pub const aria_rowcount: HtmlAttr = HtmlAttr::constant("aria-rowcount");
    pub const aria_rowindex: HtmlAttr = HtmlAttr::constant("aria-rowindex");
    pub const aria_rowspan: HtmlAttr = HtmlAttr::constant("aria-rowspan");
    pub const aria_selected: HtmlAttr = HtmlAttr::constant("aria-selected");
    pub const aria_setsize: HtmlAttr = HtmlAttr::constant("aria-setsize");
    pub const aria_sort: HtmlAttr = HtmlAttr::constant("aria-sort");
    pub const aria_valuemax: HtmlAttr = HtmlAttr::constant("aria-valuemax");
    pub const aria_valuemin: HtmlAttr = HtmlAttr::constant("aria-valuemin");
    pub const aria_valuenow: HtmlAttr = HtmlAttr::constant("aria-valuenow");
    pub const aria_valuetext: HtmlAttr = HtmlAttr::constant("aria-valuetext");
    pub const r#as: HtmlAttr = HtmlAttr::constant("as");
    pub const r#async: HtmlAttr = HtmlAttr::constant("async");
    pub const autocapitalize: HtmlAttr = HtmlAttr::constant("autocapitalize");
    pub const autocomplete: HtmlAttr = HtmlAttr::constant("autocomplete");
    pub const autocorrect: HtmlAttr = HtmlAttr::constant("autocorrect");
    pub const autofocus: HtmlAttr = HtmlAttr::constant("autofocus");
    pub const autoplay: HtmlAttr = HtmlAttr::constant("autoplay");
    pub const blocking: HtmlAttr = HtmlAttr::constant("blocking");
    pub const charset: HtmlAttr = HtmlAttr::constant("charset");
    pub const checked: HtmlAttr = HtmlAttr::constant("checked");
    pub const cite: HtmlAttr = HtmlAttr::constant("cite");
    pub const class: HtmlAttr = HtmlAttr::constant("class");
    pub const closedby: HtmlAttr = HtmlAttr::constant("closedby");
    pub const color: HtmlAttr = HtmlAttr::constant("color");
    pub const colorspace: HtmlAttr = HtmlAttr::constant("colorspace");
    pub const cols: HtmlAttr = HtmlAttr::constant("cols");
    pub const colspan: HtmlAttr = HtmlAttr::constant("colspan");
    pub const command: HtmlAttr = HtmlAttr::constant("command");
    pub const commandfor: HtmlAttr = HtmlAttr::constant("commandfor");
    pub const content: HtmlAttr = HtmlAttr::constant("content");
    pub const contenteditable: HtmlAttr = HtmlAttr::constant("contenteditable");
    pub const controls: HtmlAttr = HtmlAttr::constant("controls");
    pub const coords: HtmlAttr = HtmlAttr::constant("coords");
    pub const crossorigin: HtmlAttr = HtmlAttr::constant("crossorigin");
    pub const data: HtmlAttr = HtmlAttr::constant("data");
    pub const datetime: HtmlAttr = HtmlAttr::constant("datetime");
    pub const decoding: HtmlAttr = HtmlAttr::constant("decoding");
    pub const default: HtmlAttr = HtmlAttr::constant("default");
    pub const defer: HtmlAttr = HtmlAttr::constant("defer");
    pub const dir: HtmlAttr = HtmlAttr::constant("dir");
    pub const dirname: HtmlAttr = HtmlAttr::constant("dirname");
    pub const disabled: HtmlAttr = HtmlAttr::constant("disabled");
    pub const download: HtmlAttr = HtmlAttr::constant("download");
    pub const draggable: HtmlAttr = HtmlAttr::constant("draggable");
    pub const enctype: HtmlAttr = HtmlAttr::constant("enctype");
    pub const enterkeyhint: HtmlAttr = HtmlAttr::constant("enterkeyhint");
    pub const fetchpriority: HtmlAttr = HtmlAttr::constant("fetchpriority");
    pub const r#for: HtmlAttr = HtmlAttr::constant("for");
    pub const form: HtmlAttr = HtmlAttr::constant("form");
    pub const formaction: HtmlAttr = HtmlAttr::constant("formaction");
    pub const formenctype: HtmlAttr = HtmlAttr::constant("formenctype");
    pub const formmethod: HtmlAttr = HtmlAttr::constant("formmethod");
    pub const formnovalidate: HtmlAttr = HtmlAttr::constant("formnovalidate");
    pub const formtarget: HtmlAttr = HtmlAttr::constant("formtarget");
    pub const headers: HtmlAttr = HtmlAttr::constant("headers");
    pub const height: HtmlAttr = HtmlAttr::constant("height");
    pub const hidden: HtmlAttr = HtmlAttr::constant("hidden");
    pub const high: HtmlAttr = HtmlAttr::constant("high");
    pub const href: HtmlAttr = HtmlAttr::constant("href");
    pub const hreflang: HtmlAttr = HtmlAttr::constant("hreflang");
    pub const http_equiv: HtmlAttr = HtmlAttr::constant("http-equiv");
    pub const id: HtmlAttr = HtmlAttr::constant("id");
    pub const imagesizes: HtmlAttr = HtmlAttr::constant("imagesizes");
    pub const imagesrcset: HtmlAttr = HtmlAttr::constant("imagesrcset");
    pub const inert: HtmlAttr = HtmlAttr::constant("inert");
    pub const inputmode: HtmlAttr = HtmlAttr::constant("inputmode");
    pub const integrity: HtmlAttr = HtmlAttr::constant("integrity");
    pub const is: HtmlAttr = HtmlAttr::constant("is");
    pub const ismap: HtmlAttr = HtmlAttr::constant("ismap");
    pub const itemid: HtmlAttr = HtmlAttr::constant("itemid");
    pub const itemprop: HtmlAttr = HtmlAttr::constant("itemprop");
    pub const itemref: HtmlAttr = HtmlAttr::constant("itemref");
    pub const itemscope: HtmlAttr = HtmlAttr::constant("itemscope");
    pub const itemtype: HtmlAttr = HtmlAttr::constant("itemtype");
    pub const kind: HtmlAttr = HtmlAttr::constant("kind");
    pub const label: HtmlAttr = HtmlAttr::constant("label");
    pub const lang: HtmlAttr = HtmlAttr::constant("lang");
    pub const list: HtmlAttr = HtmlAttr::constant("list");
    pub const loading: HtmlAttr = HtmlAttr::constant("loading");
    pub const r#loop: HtmlAttr = HtmlAttr::constant("loop");
    pub const low: HtmlAttr = HtmlAttr::constant("low");
    pub const max: HtmlAttr = HtmlAttr::constant("max");
    pub const maxlength: HtmlAttr = HtmlAttr::constant("maxlength");
    pub const media: HtmlAttr = HtmlAttr::constant("media");
    pub const method: HtmlAttr = HtmlAttr::constant("method");
    pub const min: HtmlAttr = HtmlAttr::constant("min");
    pub const minlength: HtmlAttr = HtmlAttr::constant("minlength");
    pub const multiple: HtmlAttr = HtmlAttr::constant("multiple");
    pub const muted: HtmlAttr = HtmlAttr::constant("muted");
    pub const name: HtmlAttr = HtmlAttr::constant("name");
    pub const nomodule: HtmlAttr = HtmlAttr::constant("nomodule");
    pub const nonce: HtmlAttr = HtmlAttr::constant("nonce");
    pub const novalidate: HtmlAttr = HtmlAttr::constant("novalidate");
    pub const open: HtmlAttr = HtmlAttr::constant("open");
    pub const optimum: HtmlAttr = HtmlAttr::constant("optimum");
    pub const pattern: HtmlAttr = HtmlAttr::constant("pattern");
    pub const ping: HtmlAttr = HtmlAttr::constant("ping");
    pub const placeholder: HtmlAttr = HtmlAttr::constant("placeholder");
    pub const playsinline: HtmlAttr = HtmlAttr::constant("playsinline");
    pub const popover: HtmlAttr = HtmlAttr::constant("popover");
    pub const popovertarget: HtmlAttr = HtmlAttr::constant("popovertarget");
    pub const popovertargetaction: HtmlAttr = HtmlAttr::constant("popovertargetaction");
    pub const poster: HtmlAttr = HtmlAttr::constant("poster");
    pub const preload: HtmlAttr = HtmlAttr::constant("preload");
    pub const readonly: HtmlAttr = HtmlAttr::constant("readonly");
    pub const referrerpolicy: HtmlAttr = HtmlAttr::constant("referrerpolicy");
    pub const rel: HtmlAttr = HtmlAttr::constant("rel");
    pub const required: HtmlAttr = HtmlAttr::constant("required");
    pub const reversed: HtmlAttr = HtmlAttr::constant("reversed");
    pub const role: HtmlAttr = HtmlAttr::constant("role");
    pub const rows: HtmlAttr = HtmlAttr::constant("rows");
    pub const rowspan: HtmlAttr = HtmlAttr::constant("rowspan");
    pub const sandbox: HtmlAttr = HtmlAttr::constant("sandbox");
    pub const scope: HtmlAttr = HtmlAttr::constant("scope");
    pub const selected: HtmlAttr = HtmlAttr::constant("selected");
    pub const shadowrootclonable: HtmlAttr = HtmlAttr::constant("shadowrootclonable");
    pub const shadowrootcustomelementregistry: HtmlAttr = HtmlAttr::constant("shadowrootcustomelementregistry");
    pub const shadowrootdelegatesfocus: HtmlAttr = HtmlAttr::constant("shadowrootdelegatesfocus");
    pub const shadowrootmode: HtmlAttr = HtmlAttr::constant("shadowrootmode");
    pub const shadowrootserializable: HtmlAttr = HtmlAttr::constant("shadowrootserializable");
    pub const shape: HtmlAttr = HtmlAttr::constant("shape");
    pub const size: HtmlAttr = HtmlAttr::constant("size");
    pub const sizes: HtmlAttr = HtmlAttr::constant("sizes");
    pub const slot: HtmlAttr = HtmlAttr::constant("slot");
    pub const span: HtmlAttr = HtmlAttr::constant("span");
    pub const spellcheck: HtmlAttr = HtmlAttr::constant("spellcheck");
    pub const src: HtmlAttr = HtmlAttr::constant("src");
    pub const srcdoc: HtmlAttr = HtmlAttr::constant("srcdoc");
    pub const srclang: HtmlAttr = HtmlAttr::constant("srclang");
    pub const srcset: HtmlAttr = HtmlAttr::constant("srcset");
    pub const start: HtmlAttr = HtmlAttr::constant("start");
    pub const step: HtmlAttr = HtmlAttr::constant("step");
    pub const style: HtmlAttr = HtmlAttr::constant("style");
    pub const tabindex: HtmlAttr = HtmlAttr::constant("tabindex");
    pub const target: HtmlAttr = HtmlAttr::constant("target");
    pub const title: HtmlAttr = HtmlAttr::constant("title");
    pub const translate: HtmlAttr = HtmlAttr::constant("translate");
    pub const r#type: HtmlAttr = HtmlAttr::constant("type");
    pub const usemap: HtmlAttr = HtmlAttr::constant("usemap");
    pub const value: HtmlAttr = HtmlAttr::constant("value");
    pub const width: HtmlAttr = HtmlAttr::constant("width");
    pub const wrap: HtmlAttr = HtmlAttr::constant("wrap");
    pub const writingsuggestions: HtmlAttr = HtmlAttr::constant("writingsuggestions");
}

pub const ELEMENTS: &[ElementInfo] = &[
    ElementInfo::new("a", "Hyperlink.", &[115, 129, 132, 167, 176, 177, 203, 210]),
    ElementInfo::new("abbr", "Abbreviation.", &[]),
    ElementInfo::new("address", "Contact information for a page or article element.", &[]),
    ElementInfo::new("area", "Hyperlink or dead area on an image map.", &[83, 102, 115, 129, 167, 176, 177, 192, 203]),
    ElementInfo::new("article", "Self-contained syndicatable or reusable composition.", &[]),
    ElementInfo::new("aside", "Sidebar for tangentially related content.", &[]),
    ElementInfo::new("audio", "Audio player.", &[88, 101, 103, 142, 153, 173, 197]),
    ElementInfo::new("b", "Keywords.", &[]),
    ElementInfo::new("base", "Base URL and default target navigable for hyperlinks and forms.", &[131, 204]),
    ElementInfo::new("bdi", "Text directionality isolation.", &[]),
    ElementInfo::new("bdo", "Text directionality formatting.", &[]),
    ElementInfo::new("blockquote", "A section quoted from another source.", &[92]),
    ElementInfo::new("body", "Document body.", &[]),
    ElementInfo::new("br", "Line break, e.g. in poem or postal address.", &[]),
    ElementInfo::new("button", "Button control.", &[98, 99, 112, 120, 121, 122, 123, 124, 125, 154, 170, 171, 211, 217]),
    ElementInfo::new("canvas", "Scriptable bitmap canvas.", &[127, 222]),
    ElementInfo::new("caption", "Table caption.", &[]),
    ElementInfo::new("cite", "Title of a work.", &[]),
    ElementInfo::new("code", "Computer code.", &[]),
    ElementInfo::new("col", "Table column.", &[196]),
    ElementInfo::new("colgroup", "Group of columns in a table.", &[196]),
    ElementInfo::new("data", "Machine-readable equivalent.", &[218]),
    ElementInfo::new("datalist", "Container for options for combo box control.", &[]),
    ElementInfo::new("dd", "Content for corresponding dt element(s).", &[]),
    ElementInfo::new("del", "A removal from the document.", &[92, 105]),
    ElementInfo::new("details", "Disclosure control for hiding details.", &[155, 163]),
    ElementInfo::new("dfn", "Defining instance.", &[]),
    ElementInfo::new("dialog", "Dialog box or window.", &[164]),
    ElementInfo::new("div", "Generic flow container, or container for name-value groups in dl elements.", &[]),
    ElementInfo::new("dl", "Association list consisting of zero or more name-value groups.", &[]),
    ElementInfo::new("dt", "Legend for corresponding dd element(s).", &[]),
    ElementInfo::new("em", "Stress emphasis.", &[]),
    ElementInfo::new("embed", "Plugin.", &[127, 197, 212, 222]),
    ElementInfo::new("fieldset", "Group of form controls.", &[113, 120, 154]),
    ElementInfo::new("figcaption", "Caption for figure.", &[]),
    ElementInfo::new("figure", "Figure with optional caption.", &[]),
    ElementInfo::new("footer", "Footer for a page or section.", &[]),
    ElementInfo::new("form", "User-submittable form.", &[78, 79, 86, 116, 148, 156, 162, 179, 205]),
    ElementInfo::new("h1", "Heading.", &[]),
    ElementInfo::new("h2", "Heading.", &[]),
    ElementInfo::new("h3", "Heading.", &[]),
    ElementInfo::new("h4", "Heading.", &[]),
    ElementInfo::new("h5", "Heading.", &[]),
    ElementInfo::new("h6", "Heading.", &[]),
    ElementInfo::new("head", "Container for document metadata.", &[]),
    ElementInfo::new("header", "Introductory or navigational aids for a page or section.", &[]),
    ElementInfo::new("hgroup", "Heading container.", &[]),
    ElementInfo::new("hr", "Thematic break.", &[]),
    ElementInfo::new("html", "Root element.", &[]),
    ElementInfo::new("i", "Alternate voice.", &[]),
    ElementInfo::new("iframe", "Child navigable.", &[80, 81, 127, 141, 157, 176, 184, 197, 198, 222]),
    ElementInfo::new("img", "Image.", &[83, 103, 107, 117, 127, 137, 141, 176, 195, 197, 200, 216, 222]),
    ElementInfo::new("input", "Form control.", &[77, 82, 83, 87, 91, 95, 111, 112, 120, 121, 122, 123, 124, 125, 127, 140, 144, 146, 149, 151, 152, 154, 166, 168, 170, 171, 174, 180, 193, 197, 202, 213, 219, 222]),
    ElementInfo::new("ins", "An addition to the document.", &[92, 105]),
    ElementInfo::new("kbd", "User input.", &[]),
    ElementInfo::new("label", "Caption for a form control.", &[118]),
    ElementInfo::new("legend", "Caption for fieldset.", &[]),
    ElementInfo::new("li", "List item.", &[220]),
    ElementInfo::new("link", "Link metadata.", &[84, 89, 94, 103, 114, 117, 130, 132, 134, 135, 136, 147, 176, 178, 194, 210]),
    ElementInfo::new("main", "Container for the dominant contents of the document.", &[]),
    ElementInfo::new("map", "Image map.", &[158]),
    ElementInfo::new("mark", "Highlight.", &[]),
    ElementInfo::new("menu", "Menu of commands.", &[]),
    ElementInfo::new("meta", "Text metadata.", &[90, 100, 133, 147, 159]),
    ElementInfo::new("meter", "Gauge.", &[128, 143, 145, 150, 165, 221]),
    ElementInfo::new("nav", "Section with navigational links.", &[]),
    ElementInfo::new("noscript", "Fallback content for script.", &[]),
    ElementInfo::new("object", "Image, child navigable, or plugin.", &[104, 120, 127, 157, 212, 222]),
    ElementInfo::new("ol", "Ordered list.", &[181, 201, 214]),
    ElementInfo::new("optgroup", "Group of options in a list box.", &[112, 139]),
    ElementInfo::new("option", "Option in a list box or combo box control.", &[112, 139, 186, 217]),
    ElementInfo::new("output", "Calculated output value.", &[119, 120, 154]),
    ElementInfo::new("p", "Paragraph.", &[]),
    ElementInfo::new("picture", "Image.", &[]),
    ElementInfo::new("pre", "Block of preformatted text.", &[]),
    ElementInfo::new("progress", "Progress bar.", &[145, 221]),
    ElementInfo::new("q", "Quotation.", &[92]),
    ElementInfo::new("rp", "Parenthesis for ruby annotation text.", &[]),
    ElementInfo::new("rt", "Ruby annotation text.", &[]),
    ElementInfo::new("ruby", "Ruby annotation(s).", &[]),
    ElementInfo::new("s", "Inaccurate text.", &[]),
    ElementInfo::new("samp", "Computer output.", &[]),
    ElementInfo::new("script", "Embedded script.", &[85, 89, 103, 109, 117, 136, 161, 176, 197, 215]),
    ElementInfo::new("search", "Container for search controls.", &[]),
    ElementInfo::new("section", "Generic document or application section.", &[]),
    ElementInfo::new("select", "List box control.", &[87, 112, 120, 152, 154, 180, 193]),
    ElementInfo::new("slot", "Shadow tree slot.", &[160]),
    ElementInfo::new("small", "Side comment.", &[]),
    ElementInfo::new("source", "Image source for img or media source for video or audio.", &[127, 147, 195, 197, 200, 212, 222]),
    ElementInfo::new("span", "Generic phrasing container.", &[]),
    ElementInfo::new("strong", "Importance.", &[]),
    ElementInfo::new("style", "Embedded styling information.", &[89, 147]),
    ElementInfo::new("sub", "Subscript.", &[]),
    ElementInfo::new("summary", "Caption for details.", &[]),
    ElementInfo::new("sup", "Superscript.", &[]),
    ElementInfo::new("table", "Table.", &[]),
    ElementInfo::new("tbody", "Group of rows in a table.", &[]),
    ElementInfo::new("td", "Table cell.", &[97, 126, 183]),
    ElementInfo::new("template", "Template.", &[187, 188, 189, 190, 191]),
    ElementInfo::new("textarea", "Multiline text controls.", &[87, 96, 111, 112, 120, 146, 151, 154, 168, 174, 180, 182, 223]),
    ElementInfo::new("tfoot", "Group of footer rows in a table.", &[]),
    ElementInfo::new("th", "Table header cell.", &[76, 97, 126, 183, 185]),
    ElementInfo::new("thead", "Group of heading rows in a table.", &[]),
    ElementInfo::new("time", "Machine-readable equivalent of date- or time-related data.", &[106]),
    ElementInfo::new("title", "Document title.", &[]),
    ElementInfo::new("tr", "Table row.", &[]),
    ElementInfo::new("track", "Timed text track.", &[108, 138, 139, 197, 199]),
    ElementInfo::new("u", "Unarticulated annotation.", &[]),
    ElementInfo::new("ul", "List.", &[]),
    ElementInfo::new("var", "Variable.", &[]),
    ElementInfo::new("video", "Video player.", &[88, 101, 103, 127, 142, 153, 169, 172, 173, 197, 222]),
    ElementInfo::new("wbr", "Line breaking opportunity.", &[]),
];

pub const ATTRS: &[AttrInfo] = &[
    AttrInfo::new::<TokenList<char, ','>>("accesskey", "Keyboard shortcut to activate or focus element. Expects a single-codepoint string or an array thereof."),
    AttrInfo::new::<Str>("aria-activedescendant", "Identifies the currently active element when DOM focus is on a composite widget, textbox, group, or application."),
    AttrInfo::new::<StrBool>("aria-atomic", "Indicates whether assistive technologies will present all, or only parts of, the changed region based on the change notifications defined by the aria-relevant attribute."),
    AttrInfo::new::<StrOptionNone<StrEnum<255, 258>>>("aria-autocomplete", "Indicates whether inputting text could trigger display of one or more predictions of the user's intended value for an input and specifies how predictions would be presented if they are made."),
    AttrInfo::new::<StrBool>("aria-busy", "Indicates an element is being modified and that assistive technologies MAY want to wait until the modifications are complete before exposing them to the user."),
    AttrInfo::new::<Or<StrBool, StrEnum<258, 259>>>("aria-checked", "Indicates the current \"checked\" state of checkboxes, radio buttons, and other widgets. See related aria-pressed and aria-selected."),
    AttrInfo::new::<i64>("aria-colcount", "Defines the total number of columns in a table, grid, or treegrid. See related aria-colindex."),
    AttrInfo::new::<i64>("aria-colindex", "Defines an element's column index or position with respect to the total number of columns within a table, grid, or treegrid. See related aria-colcount and aria-colspan."),
    AttrInfo::new::<i64>("aria-colspan", "Defines the number of columns spanned by a cell or gridcell within a table, grid, or treegrid. See related aria-colindex and aria-rowspan."),
    AttrInfo::new::<TokenList<Str, ' '>>("aria-controls", "Identifies the element (or elements) whose contents or presence are controlled by the current element. See related aria-owns."),
    AttrInfo::new::<Or<StrBool, StrEnum<259, 264>>>("aria-current", "Indicates the element that represents the current item within a container or set of related elements."),
    AttrInfo::new::<TokenList<Str, ' '>>("aria-describedby", "Identifies the element (or elements) that describes the object. See related aria-labelledby."),
    AttrInfo::new::<Str>("aria-details", "Identifies the element that provides a detailed, extended description for the object. See related aria-describedby."),
    AttrInfo::new::<StrBool>("aria-disabled", "Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. See related aria-hidden and aria-readonly."),
    AttrInfo::new::<Str>("aria-errormessage", "Identifies the element that provides an error message for the object. See related aria-invalid and aria-describedby."),
    AttrInfo::new::<StrOptionUndefined<StrBool>>("aria-expanded", "Indicates whether the element, or another grouping element it controls, is currently expanded or collapsed."),
    AttrInfo::new::<TokenList<Str, ' '>>("aria-flowto", "Identifies the next element (or elements) in an alternate reading order of content which, at the user's discretion, allows assistive technology to override the general default of reading in document source order."),
    AttrInfo::new::<Or<StrBool, StrEnum<264, 269>>>("aria-haspopup", "Indicates the availability and type of interactive popup element, such as menu or dialog, that can be triggered by an element."),
    AttrInfo::new::<StrOptionUndefined<StrBool>>("aria-hidden", "Indicates whether the element is exposed to an accessibility API. See related aria-disabled."),
    AttrInfo::new::<Or<StrBool, StrEnum<269, 271>>>("aria-invalid", "Indicates the entered value does not conform to the format expected by the application. See related aria-errormessage."),
    AttrInfo::new::<Str>("aria-keyshortcuts", "Indicates keyboard shortcuts that an author has implemented to activate or give focus to an element."),
    AttrInfo::new::<Str>("aria-label", "Defines a string value that labels the current element. See related aria-labelledby."),
    AttrInfo::new::<TokenList<Str, ' '>>("aria-labelledby", "Identifies the element (or elements) that labels the current element. See related aria-describedby."),
    AttrInfo::new::<i64>("aria-level", "Defines the hierarchical level of an element within a structure."),
    AttrInfo::new::<StrEnum<271, 274>>("aria-live", "Indicates that an element will be updated, and describes the types of updates the user agents, assistive technologies, and user can expect from the live region."),
    AttrInfo::new::<StrBool>("aria-modal", "Indicates whether an element is modal when displayed."),
    AttrInfo::new::<StrBool>("aria-multiline", "Indicates whether a text box accepts multiple lines of input or only a single line."),
    AttrInfo::new::<StrBool>("aria-multiselectable", "Indicates that the user may select more than one item from the current selectable descendants."),
    AttrInfo::new::<StrEnum<274, 277>>("aria-orientation", "Indicates whether the element's orientation is horizontal, vertical, or unknown/ambiguous."),
    AttrInfo::new::<TokenList<Str, ' '>>("aria-owns", "Identifies an element (or elements) in order to define a visual, functional, or contextual parent/child relationship between DOM elements where the DOM hierarchy cannot be used to represent the relationship. See related aria-controls."),
    AttrInfo::new::<Str>("aria-placeholder", "Defines a short hint (a word or short phrase) intended to aid the user with data entry when the control has no value. A hint could be a sample value or a brief description of the expected format."),
    AttrInfo::new::<i64>("aria-posinset", "Defines an element's number or position in the current set of listitems or treeitems. Not required if all elements in the set are present in the DOM. See related aria-setsize."),
    AttrInfo::new::<Or<StrBool, StrEnum<258, 259>>>("aria-pressed", "Indicates the current \"pressed\" state of toggle buttons. See related aria-checked and aria-selected."),
    AttrInfo::new::<StrBool>("aria-readonly", "Indicates that the element is not editable, but is otherwise operable. See related aria-disabled."),
    AttrInfo::new::<TokenList<StrEnum<277, 282>, ' '>>("aria-relevant", "Indicates what notifications the user agent will trigger when the accessibility tree within a live region is modified. See related aria-atomic."),
    AttrInfo::new::<StrBool>("aria-required", "Indicates that user input is required on the element before a form may be submitted."),
    AttrInfo::new::<Str>("aria-roledescription", "Defines a human-readable, author-localized description for the role of an element."),
    AttrInfo::new::<i64>("aria-rowcount", "Defines the total number of rows in a table, grid, or treegrid. See related aria-rowindex."),
    AttrInfo::new::<i64>("aria-rowindex", "Defines an element's row index or position with respect to the total number of rows within a table, grid, or treegrid. See related aria-rowcount and aria-rowspan."),
    AttrInfo::new::<i64>("aria-rowspan", "Defines the number of rows spanned by a cell or gridcell within a table, grid, or treegrid. See related aria-rowindex and aria-colspan."),
    AttrInfo::new::<StrOptionUndefined<StrBool>>("aria-selected", "Indicates the current \"selected\" state of various widgets. See related aria-checked and aria-pressed."),
    AttrInfo::new::<i64>("aria-setsize", "Defines the number of items in the current set of listitems or treeitems. Not required if all elements in the set are present in the DOM. See related aria-posinset."),
    AttrInfo::new::<StrOptionNone<StrEnum<282, 285>>>("aria-sort", "Indicates if items in a table or grid are sorted in ascending or descending order."),
    AttrInfo::new::<f64>("aria-valuemax", "Defines the maximum allowed value for a range widget."),
    AttrInfo::new::<f64>("aria-valuemin", "Defines the minimum allowed value for a range widget."),
    AttrInfo::new::<f64>("aria-valuenow", "Defines the current value for a range widget. See related aria-valuetext."),
    AttrInfo::new::<Str>("aria-valuetext", "Defines the human readable text alternative of aria-valuenow for a range widget."),
    AttrInfo::new::<StrOptionNone<Or<OnOffBool, StrEnum<23, 26>>>>("autocapitalize", "Recommended autocapitalization behavior (for supported input methods)."),
    AttrInfo::new::<OnOffBool>("autocorrect", "Recommended autocorrection behavior (for supported input methods)."),
    AttrInfo::new::<NamedBool>("autofocus", "Automatically focus the element when the page is loaded."),
    AttrInfo::new::<TokenList<Str, ' '>>("class", "Classes to which the element belongs."),
    AttrInfo::new::<Or<StrBool, StrEnum<36, 37>>>("contenteditable", "Whether the element is editable."),
    AttrInfo::new::<Smart<HorizontalDir>>("dir", "The text directionality of the element."),
    AttrInfo::new::<StrBool>("draggable", "Whether the element is draggable."),
    AttrInfo::new::<StrEnum<44, 51>>("enterkeyhint", "Hint for selecting an enter key action."),
    AttrInfo::new::<Or<NamedBool, StrEnum<60, 61>>>("hidden", "Whether the element is relevant."),
    AttrInfo::new::<Str>("id", "The element's ID."),
    AttrInfo::new::<NamedBool>("inert", "Whether the element is inert."),
    AttrInfo::new::<StrOptionNone<StrEnum<66, 73>>>("inputmode", "Hint for selecting an input modality."),
    AttrInfo::new::<Str>("is", "Creates a customized built-in element."),
    AttrInfo::new::<Str>("itemid", "Global identifier for a microdata item."),
    AttrInfo::new::<TokenList<Str, ' '>>("itemprop", "Property names of a microdata item."),
    AttrInfo::new::<TokenList<Str, ' '>>("itemref", "Referenced elements."),
    AttrInfo::new::<NamedBool>("itemscope", "Introduces a microdata item."),
    AttrInfo::new::<TokenList<Str, ' '>>("itemtype", "Item types of a microdata item."),
    AttrInfo::new::<StrOptionEmpty<Str>>("lang", "Language of the element."),
    AttrInfo::new::<Str>("nonce", "Cryptographic nonce used in Content Security Policy checks."),
    AttrInfo::new::<Smart<StrEnum<80, 81>>>("popover", "Makes the element a popover element."),
    AttrInfo::new::<StrOptionNone<StrEnum<175, 255>>>("role", "An ARIA role."),
    AttrInfo::new::<Str>("slot", "The element's desired slot."),
    AttrInfo::new::<NamedBool>("spellcheck", "Whether the element is to have its spelling and grammar checked."),
    AttrInfo::new::<Str>("style", "Presentational and formatting instructions."),
    AttrInfo::new::<i64>("tabindex", "Whether the element is focusable and sequentially focusable, and the relative order of the element for the purposes of sequential focus navigation."),
    AttrInfo::new::<Str>("title", "Advisory information for the element."),
    AttrInfo::new::<YesNoBool>("translate", "Whether the element is to be translated when the page is localized."),
    AttrInfo::new::<NamedBool>("writingsuggestions", "Whether the element can offer writing suggestions or not."),
    AttrInfo::new::<Str>("abbr", "Alternative label to use for the header cell when referencing the cell in other contexts."),
    AttrInfo::new::<TokenList<Str, ','>>("accept", "Hint for expected file type in file upload controls."),
    AttrInfo::new::<StrEnum<0, 1>>("accept-charset", "Character encodings to use for form submission."),
    AttrInfo::new::<Str>("action", "URL to use for form submission."),
    AttrInfo::new::<Str>("allow", "Permissions policy to be applied to the iframe's contents."),
    AttrInfo::new::<NamedBool>("allowfullscreen", "Whether to allow the iframe's contents to use requestFullscreen()."),
    AttrInfo::new::<NamedBool>("alpha", "Allow the color's alpha component to be set."),
    AttrInfo::new::<Str>("alt", "Replacement text for use when images are not available."),
    AttrInfo::new::<StrEnum<1, 23>>("as", "Potential destination for a preload request (for rel=\"preload\" and rel=\"modulepreload\")."),
    AttrInfo::new::<NamedBool>("async", "Execute script when available, without blocking while fetching."),
    AttrInfo::new::<OnOffBool>("autocomplete", "Default setting for autofill feature for controls in the form."),
    AttrInfo::new::<Str>("autocomplete", "Hint for form autofill feature."),
    AttrInfo::new::<NamedBool>("autoplay", "Hint that the media resource can be started automatically when the page is loaded."),
    AttrInfo::new::<TokenList<Str, ' '>>("blocking", "Whether the element is potentially render-blocking."),
    AttrInfo::new::<StrEnum<0, 1>>("charset", "Character encoding declaration."),
    AttrInfo::new::<NamedBool>("checked", "Whether the control is checked."),
    AttrInfo::new::<Str>("cite", "Link to the source of the quotation or more information about the edit."),
    AttrInfo::new::<StrOptionNone<StrEnum<26, 28>>>("closedby", "Which user actions will close the dialog."),
    AttrInfo::new::<Color>("color", "Color to use when customizing a site's icon (for rel=\"mask-icon\")."),
    AttrInfo::new::<StrEnum<28, 30>>("colorspace", "The color space of the serialized color."),
    AttrInfo::new::<NonZeroU64>("cols", "Maximum number of characters per line."),
    AttrInfo::new::<NonZeroU64>("colspan", "Number of columns that the cell is to span."),
    AttrInfo::new::<Or<StrEnum<30, 36>, Str>>("command", "Indicates to the targeted element which action to take."),
    AttrInfo::new::<Str>("commandfor", "Targets another element to be invoked."),
    AttrInfo::new::<Str>("content", "Value of the element."),
    AttrInfo::new::<NamedBool>("controls", "Show user agent controls."),
    AttrInfo::new::<TokenList<f64, ',', false>>("coords", "Coordinates for the shape to be created in an image map. Expects an array of floating point numbers."),
    AttrInfo::new::<StrEnum<37, 39>>("crossorigin", "How the element handles crossorigin requests."),
    AttrInfo::new::<Str>("data", "Address of the resource."),
    AttrInfo::new::<Datetime>("datetime", "Date and (optionally) time of the change."),
    AttrInfo::new::<Or<Datetime, Duration>>("datetime", "Machine-readable value."),
    AttrInfo::new::<Smart<StrEnum<39, 41>>>("decoding", "Decoding hint to use when processing this image for presentation."),
    AttrInfo::new::<NamedBool>("default", "Enable the track if no other text track is more suitable."),
    AttrInfo::new::<NamedBool>("defer", "Defer script execution."),
    AttrInfo::new::<HorizontalDir>("dir", "The text directionality of the element."),
    AttrInfo::new::<Str>("dirname", "Name of form control to use for sending the element's directionality in form submission."),
    AttrInfo::new::<NamedBool>("disabled", "Whether the form control is disabled."),
    AttrInfo::new::<NamedBool>("disabled", "Whether the descendant form controls, except any inside legend, are disabled."),
    AttrInfo::new::<NamedBool>("disabled", "Whether the link is disabled."),
    AttrInfo::new::<Str>("download", "Whether to download the resource instead of navigating to it, and its filename if so."),
    AttrInfo::new::<StrEnum<41, 44>>("enctype", "Entry list encoding type to use for form submission."),
    AttrInfo::new::<Smart<StrEnum<51, 53>>>("fetchpriority", "Sets the priority for fetches initiated by the element."),
    AttrInfo::new::<Str>("for", "Associate the label with form control."),
    AttrInfo::new::<TokenList<Str, ' '>>("for", "Specifies controls from which the output was calculated."),
    AttrInfo::new::<Str>("form", "Associates the element with a form element."),
    AttrInfo::new::<Str>("formaction", "URL to use for form submission."),
    AttrInfo::new::<StrEnum<41, 44>>("formenctype", "Entry list encoding type to use for form submission."),
    AttrInfo::new::<StrEnum<53, 56>>("formmethod", "Variant to use for form submission."),
    AttrInfo::new::<NamedBool>("formnovalidate", "Bypass form control validation for form submission."),
    AttrInfo::new::<Or<StrEnum<56, 60>, Str>>("formtarget", "Navigable for form submission."),
    AttrInfo::new::<TokenList<Str, ' '>>("headers", "The header cells for this cell."),
    AttrInfo::new::<u64>("height", "Vertical dimension."),
    AttrInfo::new::<f64>("high", "Low limit of high range."),
    AttrInfo::new::<Str>("href", "Address of the hyperlink."),
    AttrInfo::new::<Str>("href", "Address of the hyperlink."),
    AttrInfo::new::<Str>("href", "Document base URL."),
    AttrInfo::new::<Str>("hreflang", "Language of the linked resource."),
    AttrInfo::new::<StrEnum<61, 66>>("http-equiv", "Pragma directive."),
    AttrInfo::new::<TokenList<SourceSize, ',', false>>("imagesizes", "Image sizes for different page layouts (for rel=\"preload\"). Expects an array of dictionaries with the keys `condition` (string) and `size` (length)."),
    AttrInfo::new::<TokenList<ImageCandidate, ',', false>>("imagesrcset", "Images to use in different situations, e.g., high-resolution displays, small monitors, etc. (for rel=\"preload\"). Expects an array of dictionaries with the keys `src` (string) and `width` (integer) or `density` (float)."),
    AttrInfo::new::<Str>("integrity", "Integrity metadata used in Subresource Integrity checks."),
    AttrInfo::new::<NamedBool>("ismap", "Whether the image is a server-side image map."),
    AttrInfo::new::<StrEnum<73, 78>>("kind", "The type of text track."),
    AttrInfo::new::<Str>("label", "User-visible label."),
    AttrInfo::new::<Str>("list", "List of autocomplete options."),
    AttrInfo::new::<StrEnum<78, 80>>("loading", "Used when determining loading deferral."),
    AttrInfo::new::<NamedBool>("loop", "Whether to loop the media resource."),
    AttrInfo::new::<f64>("low", "High limit of low range."),
    AttrInfo::new::<InputBound>("max", "Maximum value."),
    AttrInfo::new::<f64>("max", "Upper bound of range."),
    AttrInfo::new::<u64>("maxlength", "Maximum length of value."),
    AttrInfo::new::<Str>("media", "Applicable media."),
    AttrInfo::new::<StrEnum<53, 56>>("method", "Variant to use for form submission."),
    AttrInfo::new::<InputBound>("min", "Minimum value."),
    AttrInfo::new::<f64>("min", "Lower bound of range."),
    AttrInfo::new::<u64>("minlength", "Minimum length of value."),
    AttrInfo::new::<NamedBool>("multiple", "Whether to allow multiple values."),
    AttrInfo::new::<NamedBool>("muted", "Whether to mute the media resource by default."),
    AttrInfo::new::<Str>("name", "Name of the element to use for form submission and in the form.elements API."),
    AttrInfo::new::<Str>("name", "Name of group of mutually-exclusive details elements."),
    AttrInfo::new::<Str>("name", "Name of form to use in the document.forms API."),
    AttrInfo::new::<Or<StrEnum<56, 60>, Str>>("name", "Name of content navigable."),
    AttrInfo::new::<Str>("name", "Name of image map to reference from the usemap attribute."),
    AttrInfo::new::<Str>("name", "Metadata name."),
    AttrInfo::new::<Str>("name", "Name of shadow tree slot."),
    AttrInfo::new::<NamedBool>("nomodule", "Prevents execution in user agents that support module scripts."),
    AttrInfo::new::<NamedBool>("novalidate", "Bypass form control validation for form submission."),
    AttrInfo::new::<NamedBool>("open", "Whether the details are visible."),
    AttrInfo::new::<NamedBool>("open", "Whether the dialog box is showing."),
    AttrInfo::new::<f64>("optimum", "Optimum value in gauge."),
    AttrInfo::new::<Str>("pattern", "Pattern to be matched by the form control's value."),
    AttrInfo::new::<TokenList<Str, ' '>>("ping", "URLs to ping."),
    AttrInfo::new::<Str>("placeholder", "User-visible label to be placed within the form control."),
    AttrInfo::new::<NamedBool>("playsinline", "Encourage the user agent to display video content within the element's playback area."),
    AttrInfo::new::<Str>("popovertarget", "Targets a popover element to toggle, show, or hide."),
    AttrInfo::new::<StrEnum<81, 84>>("popovertargetaction", "Indicates whether a targeted popover element is to be toggled, shown, or hidden."),
    AttrInfo::new::<Str>("poster", "Poster frame to show prior to video playback."),
    AttrInfo::new::<Smart<StrOptionNone<StrEnum<77, 78>>>>("preload", "Hints how much buffering the media resource will likely need."),
    AttrInfo::new::<NamedBool>("readonly", "Whether to allow the value to be edited by the user."),
    AttrInfo::new::<NamedBool>("readonly", "Affects willValidate, plus any behavior added by the custom element author."),
    AttrInfo::new::<StrOptionEmpty<StrEnum<84, 92>>>("referrerpolicy", "Referrer policy for fetches initiated by the element."),
    AttrInfo::new::<TokenList<StrEnum<92, 119>, ' '>>("rel", "Relationship between the location in the document containing the hyperlink and the destination resource."),
    AttrInfo::new::<TokenList<StrEnum<92, 119>, ' '>>("rel", "Relationship between the document containing the hyperlink and the destination resource."),
    AttrInfo::new::<TokenList<StrEnum<92, 119>, ' '>>("rel", "Relationship between the document containing the form and its action destination"),
    AttrInfo::new::<NamedBool>("required", "Whether the control is required for form submission."),
    AttrInfo::new::<NamedBool>("reversed", "Number the list backwards."),
    AttrInfo::new::<NonZeroU64>("rows", "Number of lines to show."),
    AttrInfo::new::<u64>("rowspan", "Number of rows that the cell is to span."),
    AttrInfo::new::<TokenList<StrEnum<119, 132>, ' '>>("sandbox", "Security rules for nested content."),
    AttrInfo::new::<StrEnum<132, 136>>("scope", "Specifies which cells the header cell applies to."),
    AttrInfo::new::<NamedBool>("selected", "Whether the option is selected by default."),
    AttrInfo::new::<NamedBool>("shadowrootclonable", "Sets clonable on a declarative shadow root."),
    AttrInfo::new::<NamedBool>("shadowrootcustomelementregistry", "Enables declarative shadow roots to indicate they will use a custom element registry."),
    AttrInfo::new::<NamedBool>("shadowrootdelegatesfocus", "Sets delegates focus on a declarative shadow root."),
    AttrInfo::new::<StrEnum<136, 138>>("shadowrootmode", "Enables streaming declarative shadow roots."),
    AttrInfo::new::<NamedBool>("shadowrootserializable", "Sets serializable on a declarative shadow root."),
    AttrInfo::new::<StrEnum<138, 142>>("shape", "The kind of shape to be created in an image map."),
    AttrInfo::new::<NonZeroU64>("size", "Size of the control."),
    AttrInfo::new::<TokenList<IconSize, ' ', false>>("sizes", "Sizes of the icons (for rel=\"icon\"). Expects an array of sizes. Each size is specified as an array of two integers (width and height)."),
    AttrInfo::new::<TokenList<SourceSize, ',', false>>("sizes", "Image sizes for different page layouts. Expects an array of dictionaries with the keys `condition` (string) and `size` (length)."),
    AttrInfo::new::<NonZeroU64>("span", "Number of columns spanned by the element."),
    AttrInfo::new::<Str>("src", "Address of the resource."),
    AttrInfo::new::<Str>("srcdoc", "A document to render in the iframe."),
    AttrInfo::new::<Str>("srclang", "Language of the text track."),
    AttrInfo::new::<TokenList<ImageCandidate, ',', false>>("srcset", "Images to use in different situations, e.g., high-resolution displays, small monitors, etc. Expects an array of dictionaries with the keys `src` (string) and `width` (integer) or `density` (float)."),
    AttrInfo::new::<i64>("start", "Starting value of the list."),
    AttrInfo::new::<Or<PositiveF64, StrEnum<26, 27>>>("step", "Granularity to be matched by the form control's value."),
    AttrInfo::new::<Or<StrEnum<56, 60>, Str>>("target", "Navigable for hyperlink navigation."),
    AttrInfo::new::<Or<StrEnum<56, 60>, Str>>("target", "Default navigable for hyperlink navigation and form submission."),
    AttrInfo::new::<Or<StrEnum<56, 60>, Str>>("target", "Navigable for form submission."),
    AttrInfo::new::<Str>("title", "Full term or expansion of abbreviation."),
    AttrInfo::new::<Str>("title", "Description of pattern (when used with pattern attribute)."),
    AttrInfo::new::<Str>("title", "Title of the link."),
    AttrInfo::new::<Str>("title", "CSS style sheet set name."),
    AttrInfo::new::<Str>("type", "Hint for the type of the referenced resource."),
    AttrInfo::new::<StrEnum<142, 145>>("type", "Type of button."),
    AttrInfo::new::<Str>("type", "Type of embedded resource."),
    AttrInfo::new::<StrEnum<145, 167>>("type", "Type of form control."),
    AttrInfo::new::<StrEnum<167, 172>>("type", "Kind of list marker."),
    AttrInfo::new::<Or<StrEnum<172, 173>, Str>>("type", "Type of script."),
    AttrInfo::new::<Str>("usemap", "Name of image map to use."),
    AttrInfo::new::<Str>("value", "Value to be used for form submission."),
    AttrInfo::new::<Str>("value", "Machine-readable value."),
    AttrInfo::new::<InputValue>("value", "Value of the form control."),
    AttrInfo::new::<i64>("value", "Ordinal value of the list item."),
    AttrInfo::new::<f64>("value", "Current value of the element."),
    AttrInfo::new::<u64>("width", "Horizontal dimension."),
    AttrInfo::new::<StrEnum<173, 175>>("wrap", "How the value of the form control is to be wrapped for form submission."),
];

pub const ATTRS_GLOBAL: usize = 76;

pub const ATTR_STRINGS: &[(&str, &str)] = &[
    ("utf-8", ""),
    ("audio", ""),
    ("audioworklet", ""),
    ("document", ""),
    ("embed", ""),
    ("font", ""),
    ("frame", ""),
    ("iframe", ""),
    ("image", ""),
    ("json", ""),
    ("manifest", ""),
    ("object", ""),
    ("paintworklet", ""),
    ("report", ""),
    ("script", ""),
    ("serviceworker", ""),
    ("sharedworker", ""),
    ("style", ""),
    ("track", ""),
    ("video", ""),
    ("webidentity", ""),
    ("worker", ""),
    ("xslt", ""),
    ("sentences", ""),
    ("words", ""),
    ("characters", ""),
    ("any", ""),
    ("closerequest", ""),
    ("limited-srgb", ""),
    ("display-p3", ""),
    ("toggle-popover", ""),
    ("show-popover", ""),
    ("hide-popover", ""),
    ("close", ""),
    ("request-close", ""),
    ("show-modal", ""),
    ("plaintext-only", ""),
    ("anonymous", ""),
    ("use-credentials", ""),
    ("sync", ""),
    ("async", ""),
    ("application/x-www-form-urlencoded", ""),
    ("multipart/form-data", ""),
    ("text/plain", ""),
    ("enter", ""),
    ("done", ""),
    ("go", ""),
    ("next", ""),
    ("previous", ""),
    ("search", ""),
    ("send", ""),
    ("high", ""),
    ("low", ""),
    ("GET", ""),
    ("POST", ""),
    ("dialog", ""),
    ("_blank", ""),
    ("_self", ""),
    ("_parent", ""),
    ("_top", ""),
    ("until-found", ""),
    ("content-type", ""),
    ("default-style", ""),
    ("refresh", ""),
    ("x-ua-compatible", ""),
    ("content-security-policy", ""),
    ("text", ""),
    ("tel", ""),
    ("email", ""),
    ("url", ""),
    ("numeric", ""),
    ("decimal", ""),
    ("search", ""),
    ("subtitles", ""),
    ("captions", ""),
    ("descriptions", ""),
    ("chapters", ""),
    ("metadata", ""),
    ("lazy", ""),
    ("eager", ""),
    ("manual", ""),
    ("toggle", ""),
    ("show", ""),
    ("hide", ""),
    ("no-referrer", ""),
    ("no-referrer-when-downgrade", ""),
    ("same-origin", ""),
    ("origin", ""),
    ("strict-origin", ""),
    ("origin-when-cross-origin", ""),
    ("strict-origin-when-cross-origin", ""),
    ("unsafe-url", ""),
    ("alternate", ""),
    ("canonical", ""),
    ("author", ""),
    ("bookmark", ""),
    ("dns-prefetch", ""),
    ("expect", ""),
    ("external", ""),
    ("help", ""),
    ("icon", ""),
    ("manifest", ""),
    ("modulepreload", ""),
    ("license", ""),
    ("next", ""),
    ("nofollow", ""),
    ("noopener", ""),
    ("noreferrer", ""),
    ("opener", ""),
    ("pingback", ""),
    ("preconnect", ""),
    ("prefetch", ""),
    ("preload", ""),
    ("prev", ""),
    ("privacy-policy", ""),
    ("search", ""),
    ("stylesheet", ""),
    ("tag", ""),
    ("terms-of-service", ""),
    ("allow-downloads", ""),
    ("allow-forms", ""),
    ("allow-modals", ""),
    ("allow-orientation-lock", ""),
    ("allow-pointer-lock", ""),
    ("allow-popups", ""),
    ("allow-popups-to-escape-sandbox", ""),
    ("allow-presentation", ""),
    ("allow-same-origin", ""),
    ("allow-scripts", ""),
    ("allow-top-navigation", ""),
    ("allow-top-navigation-by-user-activation", ""),
    ("allow-top-navigation-to-custom-protocols", ""),
    ("row", ""),
    ("col", ""),
    ("rowgroup", ""),
    ("colgroup", ""),
    ("open", ""),
    ("closed", ""),
    ("circle", ""),
    ("default", ""),
    ("poly", ""),
    ("rect", ""),
    ("submit", ""),
    ("reset", ""),
    ("button", ""),
    ("hidden", ""),
    ("text", ""),
    ("search", ""),
    ("tel", ""),
    ("url", ""),
    ("email", ""),
    ("password", ""),
    ("date", ""),
    ("month", ""),
    ("week", ""),
    ("time", ""),
    ("datetime-local", ""),
    ("number", ""),
    ("range", ""),
    ("color", ""),
    ("checkbox", ""),
    ("radio", ""),
    ("file", ""),
    ("submit", ""),
    ("image", ""),
    ("reset", ""),
    ("button", ""),
    ("1", ""),
    ("a", ""),
    ("A", ""),
    ("i", ""),
    ("I", ""),
    ("module", ""),
    ("soft", ""),
    ("hard", ""),
    ("alert", "A type of live region with important, and usually time-sensitive, information. See related alertdialog and status."),
    ("alertdialog", "A type of dialog that contains an alert message, where initial focus goes to an element within the dialog. See related alert and dialog."),
    ("application", "A structure containing one or more focusable elements requiring user input, such as keyboard or gesture events, that do not follow a standard interaction pattern supported by a widget role."),
    ("article", "A section of a page that consists of a composition that forms an independent part of a document, page, or site."),
    ("banner", "A region that contains mostly site-oriented content, rather than page-specific content."),
    ("button", "An input that allows for user-triggered actions when clicked or pressed. See related link."),
    ("cell", "A cell in a tabular container. See related gridcell."),
    ("checkbox", "A checkable input that has three possible values: true, false, or mixed."),
    ("columnheader", "A cell containing header information for a column."),
    ("combobox", "A composite widget containing a single-line textbox and another element, such as a listbox or grid, that can dynamically pop up to help the user set the value of the textbox."),
    ("command", "A form of widget that performs an action but does not receive input data."),
    ("complementary", "A supporting section of the document, designed to be complementary to the main content at a similar level in the DOM hierarchy, but remains meaningful when separated from the main content."),
    ("composite", "A widget that may contain navigable descendants or owned children."),
    ("contentinfo", "A large perceivable region that contains information about the parent document."),
    ("definition", "A definition of a term or concept. See related term."),
    ("dialog", "A dialog is a descendant window of the primary window of a web application. For HTML pages, the primary application window is the entire web document, i.e., the body element."),
    ("directory", "A list of references to members of a group, such as a static table of contents."),
    ("document", "An element containing content that assistive technology users may want to browse in a reading mode."),
    ("feed", "A scrollable list of articles where scrolling may cause articles to be added to or removed from either end of the list."),
    ("figure", "A perceivable section of content that typically contains a graphical document, images, code snippets, or example text. The parts of a figure MAY be user-navigable."),
    ("form", "A landmark region that contains a collection of items and objects that, as a whole, combine to create a form. See related search."),
    ("grid", "A composite widget containing a collection of one or more rows with one or more cells where some or all cells in the grid are focusable by using methods of two-dimensional navigation, such as directional arrow keys."),
    ("gridcell", "A cell in a grid or treegrid."),
    ("group", "A set of user interface objects which are not intended to be included in a page summary or table of contents by assistive technologies."),
    ("heading", "A heading for a section of the page."),
    ("img", "A container for a collection of elements that form an image."),
    ("input", "A generic type of widget that allows user input."),
    ("landmark", "A perceivable section containing content that is relevant to a specific, author-specified  purpose and sufficiently important that users will likely want to be able to navigate to the section easily and to have it listed in a summary of the page. Such a page summary could be generated dynamically by a user agent or assistive technology."),
    ("link", "An interactive reference to an internal or external resource that, when activated, causes the user agent to navigate to that resource. See related button."),
    ("list", "A section containing listitem elements. See related listbox."),
    ("listbox", "A widget that allows the user to select one or more items from a list of choices. See related combobox and list."),
    ("listitem", "A single item in a list or directory."),
    ("log", "A type of live region where new information is added in meaningful order and old information may disappear. See related marquee."),
    ("main", "The main content of a document."),
    ("marquee", "A type of live region where non-essential information changes frequently. See related log."),
    ("math", "Content that represents a mathematical expression."),
    ("menu", "A type of widget that offers a list of choices to the user."),
    ("menubar", "A presentation of menu that usually remains visible and is usually presented horizontally."),
    ("menuitem", "An option in a set of choices contained by a menu or menubar."),
    ("menuitemcheckbox", "A menuitem with a checkable state whose possible values are true, false, or mixed."),
    ("menuitemradio", "A checkable menuitem in a set of elements with the same role, only one of which can be checked at a time."),
    ("navigation", "A collection of navigational elements (usually links) for navigating the document or related documents."),
    ("note", "A section whose content is parenthetic or ancillary to the main content of the resource."),
    ("option", "A selectable item in a select list."),
    ("presentation", "An element whose implicit native role semantics will not be mapped to the accessibility API. See synonym none."),
    ("progressbar", "An element that displays the progress status for tasks that take a long time."),
    ("radio", "A checkable input in a group of elements with the same role, only one of which can be checked at a time."),
    ("radiogroup", "A group of radio buttons."),
    ("range", "An input representing a range of values that can be set by the user."),
    ("region", "A perceivable section containing content that is relevant to a specific, author-specified  purpose and sufficiently important that users will likely want to be able to navigate to the section easily and to have it listed in a summary of the page. Such a page summary could be generated dynamically by a user agent or assistive technology."),
    ("roletype", "The base role from which all other roles in this taxonomy inherit."),
    ("row", "A row of cells in a tabular container."),
    ("rowgroup", "A structure containing one or more row elements in a tabular container."),
    ("rowheader", "A cell containing header information for a row in a grid."),
    ("scrollbar", "A graphical object that controls the scrolling of content within a viewing area, regardless of whether the content is fully displayed within the viewing area."),
    ("search", "A landmark region that contains a collection of items and objects that, as a whole, combine to create a search facility. See related form and searchbox."),
    ("searchbox", "A type of textbox intended for specifying search criteria. See related textbox and search."),
    ("section", "A renderable structural containment unit in a document or application."),
    ("sectionhead", "A structure that labels or summarizes the topic of its related section."),
    ("select", "A form widget that allows the user to make selections from a set of choices."),
    ("separator", "A divider that separates and distinguishes sections of content or groups of menuitems."),
    ("slider", "A user input where the user selects a value from within a given range."),
    ("spinbutton", "A form of range that expects the user to select from among discrete choices."),
    ("status", "A type of live region whose content is advisory information for the user but is not important enough to justify an alert, often but not necessarily presented as a status bar."),
    ("structure", "A document structural element."),
    ("switch", "A type of checkbox that represents on/off values, as opposed to checked/unchecked values. See related checkbox."),
    ("tab", "A grouping label providing a mechanism for selecting the tab content that is to be rendered to the user."),
    ("table", "A section containing data arranged in rows and columns. See related grid."),
    ("tablist", "A list of tab elements, which are references to tabpanel elements."),
    ("tabpanel", "A container for the resources associated with a tab, where each tab is contained in a tablist."),
    ("term", "A word or phrase with a corresponding definition. See related definition."),
    ("textbox", "A type of input that allows free-form text as its value."),
    ("timer", "A type of live region containing a numerical counter which indicates an amount of elapsed time from a start point, or the time remaining until an end point."),
    ("toolbar", "A collection of commonly used function buttons or controls represented in compact visual form."),
    ("tooltip", "A contextual popup that displays a description for an element."),
    ("tree", "A type of list that may contain sub-level nested groups that can be collapsed and expanded."),
    ("treegrid", "A grid whose rows can be expanded and collapsed in the same manner as for a tree."),
    ("treeitem", "An option item of a tree. This is an element within a tree that may be expanded or collapsed if it contains a sub-level group of tree item elements."),
    ("widget", "An interactive component of a graphical user interface (GUI)."),
    ("window", "A browser or application window."),
    ("inline", "When a user is providing input, text suggesting one way to complete the provided input may be dynamically inserted after the caret."),
    ("list", "When a user is providing input, an element containing a collection of values that could complete the provided input may be displayed."),
    ("both", "When a user is providing input, an element containing a collection of values that could complete the provided input may be displayed. If displayed, one value in the collection is automatically selected, and the text needed to complete the automatically selected value appears after the caret in the input."),
    ("mixed", "An intermediate value between true and false."),
    ("page", "Represents the current page within a set of pages."),
    ("step", "Represents the current step within a process."),
    ("location", "Represents the current location within an environment or context."),
    ("date", "Represents the current date within a collection of dates."),
    ("time", "Represents the current time within a set of times."),
    ("menu", "Indicates the popup is a menu."),
    ("listbox", "Indicates the popup is a listbox."),
    ("tree", "Indicates the popup is a tree."),
    ("grid", "Indicates the popup is a grid."),
    ("dialog", "Indicates the popup is a dialog."),
    ("grammar", "A grammatical error was detected."),
    ("spelling", "A spelling error was detected."),
    ("assertive", "Indicates that updates to the region have the highest priority and should be presented the user immediately."),
    ("off", "Indicates that updates to the region should not be presented to the user unless the used is currently focused on that region."),
    ("polite", "Indicates that updates to the region should be presented at the next graceful opportunity, such as at the end of speaking the current sentence or when the user pauses typing."),
    ("horizontal", "The element is oriented horizontally."),
    ("undefined", "The element's orientation is unknown/ambiguous."),
    ("vertical", "The element is oriented vertically."),
    ("additions", "Element nodes are added to the accessibility tree within the live region."),
    ("additions text", "Equivalent to the combination of values, \"additions text\"."),
    ("all", "Equivalent to the combination of all values, \"additions removals text\"."),
    ("removals", "Text content, a text alternative, or an element node within the live region is removed from the accessibility tree."),
    ("text", "Text content or a text alternative is added to any descendant in the accessibility tree of the live region."),
    ("ascending", "Items are sorted in ascending order by this column."),
    ("descending", "Items are sorted in descending order by this column."),
    ("other", "A sort algorithm other than ascending or descending has been applied."),
];
