authors = ["Mr Robert", "Miss Enola", "Mr Jonathan"]
version = "1.0.3"

series = [
    { name = "attack on titan", fans = 500},
    { name = "demon slayer", fans = 10}
]

[informations]
location = "room A204"
pages = 47