string = "wonderful"
integer = 42
float = 3.14
boolean = true
date_time = 2023-02-01T15:38:57Z
date_time2 = 2023-02-01T15:38:57
date = 2023-02-01
time = 15:38:57
array = [1, "string", 3.0, false]
inline_table = { first = "amazing", second = "greater" }

[table]
element = 5
others = [false, "indeed", 7]
