server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    index index.html;
    root /usr/share/nginx/html;

    # redirect .html URLs to same page without html suffix.
    location ~ ^(.+)\.html$ {
        return 301 $1;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
