# Based on ripgrep's release action:
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: Create Release Assets
on:
  release:
    types: [published]

jobs:
  build-binaries:
    name: Build ${{ matrix.target }} binary
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - target: armv7-unknown-linux-musleabi
            os: ubuntu-latest
            cross: true
          - target: riscv64gc-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
          - target: x86_64-apple-darwin
            os: macos-latest
            cross: false
          - target: aarch64-apple-darwin
            os: macos-latest
            cross: false
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            cross: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@e081816240890017053eacbb1bdf337761dc5582 # 1.95.0
        with:
          target: ${{ matrix.target }}

      - name: Run Cross
        if: ${{ matrix.cross }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross.git --locked --rev 085092ca
          # Suppress getrandom 0.2/0.3 NetBSD metadata conflict warning (doesn't
          # affect us). We can't currently unify the depencencies because
          # unicode_names2 is not compatible with getrandom 0.3.
          CROSS_NO_WARNINGS=0 cross build -p typst-cli --release --target "${{ matrix.target }}" --features self-update,vendor-openssl

      - name: Run Cargo
        if: ${{ !matrix.cross }}
        run: cargo build -p typst-cli --release --target "${{ matrix.target }}" --features self-update

      - name: Create artifact directory
        shell: bash
        run: |
          TARGET_DIR="target/${{ matrix.target }}/release"
          ARCHIVE_DIR="typst-${{ matrix.target }}"
          mkdir "$ARCHIVE_DIR"
          cp README.md LICENSE NOTICE "$ARCHIVE_DIR"
          if [ -f "$TARGET_DIR/typst.exe" ]; then
            ARCHIVE="$ARCHIVE_DIR.zip"
            cp "$TARGET_DIR/typst.exe" "$ARCHIVE_DIR"
            7z a -r "$ARCHIVE" "$ARCHIVE_DIR"
          else
            ARCHIVE="$ARCHIVE_DIR.tar.xz"
            cp "$TARGET_DIR/typst" "$ARCHIVE_DIR"
            tar cJf "$ARCHIVE" "$ARCHIVE_DIR"
          fi
          echo "ARCHIVE=$ARCHIVE" >> "$GITHUB_ENV"

      - name: Upload asset
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="${{ github.ref_name }}"
          gh release upload "$VERSION" "$ARCHIVE"

  build-docs:
    name: Build documentation (PDF)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@e081816240890017053eacbb1bdf337761dc5582 # 1.95.0

      - name: Compile documentation
        run: cargo docit compile --format pdf --release

      - name: Rename documentation file
        run: mv docs/dist/docs.pdf typst-documentation.pdf

      - name: Upload asset
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="${{ github.ref_name }}"
          gh release upload "$VERSION" typst-documentation.pdf
